[package]
name = "multithreaded_download_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
indicatif = "0.17.11"
reqwest = {version = "0.12.12", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.4"
